name: Run Tests and Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-tests-and-linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, json, pdo_mysql, redis
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs --standard=PSR12 src/

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse src/ --level=7

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml
